import type { ReviewItem } from './types';

export const REVIEWS_PER_PAGE = 7;

export const INITIAL_REVIEWS: ReviewItem[] = [
  {
    id: '1',
    reviewId: 'REV-001',
    product: 'Luxury Arabic Oud',
    buyerName: 'Ahmed Al-Sayed',
    vendor: 'Al Falah Crafts',
    rating: 5,
    date: '2025-01-10',
  },
  {
    id: '2',
    reviewId: 'REV-002',
    product: 'Handwoven Wool Rug',
    buyerName: 'Sara Hassan',
    vendor: 'Dubai Textiles Hub',
    rating: 4,
    date: '2025-01-09',
  },
  {
    id: '3',
    reviewId: 'REV-003',
    product: 'Premium Khalas Dates',
    buyerName: 'Omar Khalil',
    vendor: 'Dates & Co',
    rating: 3,
    date: '2025-01-08',
  },
  {
    id: '4',
    reviewId: 'REV-004',
    product: 'Vintage Leather Tote',
    buyerName: 'Fatima Noor',
    vendor: 'Red Souk',
    rating: 2,
    date: '2025-01-07',
  },
  {
    id: '5',
    reviewId: 'REV-005',
    product: 'Ceramic Garden Plate',
    buyerName: 'Layla Ibrahim',
    vendor: 'Deep Roots',
    rating: 5,
    date: '2025-01-06',
  },
  {
    id: '6',
    reviewId: 'REV-006',
    product: 'Organic Argan Oil',
    buyerName: 'Youssef Ali',
    vendor: 'Beauty Lab',
    rating: 2,
    date: '2025-01-05',
  },
  {
    id: '7',
    reviewId: 'REV-007',
    product: 'Silver Arabesque Cuff',
    buyerName: 'Nadia Mostafa',
    vendor: 'Artisan Collective',
    rating: 4,
    date: '2025-01-04',
  },
  {
    id: '8',
    reviewId: 'REV-008',
    product: 'Ceramic Garden Plate',
    buyerName: 'Layla Ibrahim',
    vendor: 'Deep Roots',
    rating: 5,
    date: '2025-01-06',
  },
  {
    id: '9',
    reviewId: 'REV-009',
    product: 'Organic Argan Oil',
    buyerName: 'Youssef Ali',
    vendor: 'Beauty Lab',
    rating: 2,
    date: '2025-01-05',
  },
  {
    id: '10',
    reviewId: 'REV-010',
    product: 'Silver Arabesque Cuff',
    buyerName: 'Nadia Mostafa',
    vendor: 'Artisan Collective',
    rating: 4,
    date: '2025-01-04',
  }
];
