import type { VoucherItem } from './types';
import { getVoucherStatus } from './utils';

export const VOUCHERS_PER_PAGE = 20;

const RAW_INITIAL_VOUCHERS: VoucherItem[] = [
  {
    id: '1',
    code: 'WELCOME20',
    type: 'Percentage',
    discount: '20%',
    discountValue: 20,
    minOrder: 'SAR 100',
    maxDiscount: 'SAR 50',
    usage: '145/500',
    usedCount: 145,
    maxUsage: 500,
    expiryDate: '2026-12-31',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '2',
    code: 'FREESHIP',
    type: 'Free Shipping',
    discount: '—',
    discountValue: 0,
    minOrder: 'SAR 200',
    maxDiscount: '—',
    usage: '89/200',
    usedCount: 89,
    maxUsage: 200,
    expiryDate: '2026-09-15',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '3',
    code: 'SAVE50',
    type: 'Amount',
    discount: 'SAR 50',
    discountValue: 50,
    minOrder: 'SAR 300',
    maxDiscount: '—',
    usage: '200/200',
    usedCount: 200,
    maxUsage: 200,
    expiryDate: '2025-01-30',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
  {
    id: '4',
    code: 'VIP10',
    type: 'Percentage',
    discount: '10%',
    discountValue: 10,
    minOrder: 'SAR 50',
    maxDiscount: 'SAR 100',
    usage: '56/100',
    usedCount: 56,
    maxUsage: 100,
    expiryDate: '2026-10-01',
    status: 'Active',
    limitOnePerCustomer: true,
  },
  {
    id: '5',
    code: 'SUMMER30',
    type: 'Percentage',
    discount: '30%',
    discountValue: 30,
    minOrder: 'SAR 150',
    maxDiscount: 'SAR 75',
    usage: '0/300',
    usedCount: 0,
    maxUsage: 300,
    expiryDate: '2026-08-30',
    status: 'Active',
    limitOnePerCustomer: false,
  },
  {
    id: '6',
    code: 'FLAT100',
    type: 'Amount',
    discount: 'SAR 100',
    discountValue: 100,
    minOrder: 'SAR 500',
    maxDiscount: '—',
    usage: '45/100',
    usedCount: 45,
    maxUsage: 100,
    expiryDate: '2024-12-31',
    status: 'Expired',
    limitOnePerCustomer: true,
  },
];

export const INITIAL_VOUCHERS: VoucherItem[] = RAW_INITIAL_VOUCHERS.map((v) => ({
  ...v,
  status: getVoucherStatus(v.expiryDate, v.status),
}));

