import type { Vendor } from './vendors';

export const VENDOR_CATEGORIES = [
  'Handicrafts',
  'Florals',
  'Electronics',
  'Apparel',
  'Food',
  'Beauty',
  'Sports',
  'Home & Garden',
  'Fashion',
];

export const INITIAL_VENDORS: Vendor[] = [
  // ── Pending ──────────────────────────────────────
  {
    id: 1,
    businessName: 'Al-Fatah Crafts',
    owner: 'Ibrahim Ali',
    email: 'info@alfatah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Handicrafts',
    status: 'pending',
  },
  {
    id: 2,
    businessName: 'Desert Bloom',
    owner: 'Sarah Mansour',
    email: 'sarah@desertbloom.com',
    submittedDate: 'Oct 21, 2024',
    category: 'Florals',
    status: 'pending',
  },
  {
    id: 3,
    businessName: 'Desert Bloom',
    owner: 'Sarah Mansour',
    email: 'sarah@desertbloom.com',
    submittedDate: 'Oct 21, 2024',
    category: 'Florals',
    status: 'pending',
  },
  {
    id: 4,
    businessName: 'Oasis Tech',
    owner: 'Khalid Fahad',
    email: 'khalid@oasistech.sa',
    submittedDate: 'Oct 20, 2024',
    category: 'Electronics',
    status: 'pending',
  },
  {
    id: 5,
    businessName: 'Red Sea Styles',
    owner: 'Layla Hassan',
    email: 'layla@redsea.com',
    submittedDate: 'Oct 19, 2024',
    category: 'Apparel',
    status: 'pending',
  },
  {
    id: 6,
    businessName: 'Red Sea Styles',
    owner: 'Layla Hassan',
    email: 'layla@redsea.com',
    submittedDate: 'Oct 19, 2024',
    category: 'Apparel',
    status: 'pending',
  },
  {
    id: 7,
    businessName: 'Dates & Co',
    owner: 'Ahmed Saeed',
    email: 'ahmed@datesco.sa',
    submittedDate: 'Oct 18, 2024',
    category: 'Food',
    status: 'pending',
  },

  // ── Approved (All Vendors) ────────────────────────
  {
    id: 8,
    businessName: 'Urban Elegance',
    owner: 'Noura Al-Said',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Fashion',
    status: 'approved',
    revenue: 452390,
    orders: 1842,
    active: true,
  },
  {
    id: 9,
    businessName: 'Urban Elegance',
    owner: 'Noura Al-Said',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Fashion',
    status: 'approved',
    revenue: 452390,
    orders: 1842,
    active: true,
  },
  {
    id: 10,
    businessName: 'Urban Elegance',
    owner: 'Noura Al-Said',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Fashion',
    status: 'approved',
    revenue: 452390,
    orders: 1842,
    active: true,
  },
  {
    id: 11,
    businessName: 'Sajek Styles',
    owner: 'Ahmed Sajek',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Apparel',
    status: 'approved',
    revenue: 124500,
    orders: 890,
    active: true,
  },
  {
    id: 12,
    businessName: 'Sajek Styles',
    owner: 'Ahmed Sajek',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Apparel',
    status: 'approved',
    revenue: 124500,
    orders: 890,
    active: true,
  },
  {
    id: 13,
    businessName: 'Sajek Styles',
    owner: 'Ahmed Sajek',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Apparel',
    status: 'approved',
    revenue: 124500,
    orders: 890,
    active: true,
  },
  {
    id: 14,
    businessName: 'Vintage Vault',
    owner: 'Layla Ibrahim',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Handicrafts',
    status: 'approved',
    revenue: 12400,
    orders: 120,
    active: true,
  },
  {
    id: 15,
    businessName: 'Vintage Vault',
    owner: 'Layla Ibrahim',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Handicrafts',
    status: 'approved',
    revenue: 12400,
    orders: 120,
    active: true,
  },
  {
    id: 16,
    businessName: 'Vintage Vault',
    owner: 'Layla Ibrahim',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Handicrafts',
    status: 'approved',
    revenue: 12400,
    orders: 120,
    active: true,
  },
  {
    id: 17,
    businessName: 'Eco Living',
    owner: 'Khalid Mansour',
    email: 'info@alfalah.sa',
    submittedDate: 'Oct 22, 2024',
    category: 'Home & Garden',
    status: 'approved',
    revenue: 89200,
    orders: 620,
    active: true,
  },
  {
    id: 18,
    businessName: 'Saffron House',
    owner: 'Nora Al-Rashid',
    email: 'nora@saffronhouse.sa',
    submittedDate: 'Oct 17, 2024',
    category: 'Food',
    status: 'approved',
    revenue: 54800,
    orders: 340,
    active: true,
  },
  {
    id: 19,
    businessName: 'Gulf Gadgets',
    owner: 'Faisal Nasser',
    email: 'faisal@gulfgadgets.com',
    submittedDate: 'Oct 16, 2024',
    category: 'Electronics',
    status: 'approved',
    revenue: 312000,
    orders: 1120,
    active: false,
  },
  {
    id: 20,
    businessName: 'Pearl Beauty',
    owner: 'Hana Al-Amin',
    email: 'hana@pearlbeauty.sa',
    submittedDate: 'Oct 15, 2024',
    category: 'Beauty',
    status: 'approved',
    revenue: 78600,
    orders: 445,
    active: true,
  },

  // ── Suspended ─────────────────────────────────────
  {
    id: 21,
    businessName: 'Riyadh Rugs',
    owner: 'Omar Khalil',
    email: 'omar@riyadhrugs.sa',
    submittedDate: 'Oct 14, 2024',
    category: 'Home & Garden',
    status: 'suspended',
  },
  {
    id: 22,
    businessName: 'Al-Noor Sports',
    owner: 'Tariq Salam',
    email: 'tariq@alnoor.sa',
    submittedDate: 'Oct 13, 2024',
    category: 'Sports',
    status: 'suspended',
  },
];
